platform :ios, '8.0'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
    end
  end
end

target 'Leanplum-iOS-Location_Example' do
  pod 'Leanplum-iOS-Location', :path => '../'
  pod 'Leanplum-iOS-SDK'
end

target 'Leanplum-iOS-LocationAndBeacons_Example' do
    pod 'Leanplum-iOS-LocationAndBeacons', :path => '../'
    pod 'Leanplum-iOS-SDK'
    
    target 'Leanplum-iOS-Location_Tests' do
        pod 'OCMock', '~> 3.3.1'
    end
end
