inhibit_all_warnings!

target 'Leanplum-iOS-Location_Example' do
  platform :ios, '6.0'
  pod 'Leanplum-iOS-Location-source', :path => '../'
  pod 'Leanplum-iOS-SDK-source', :path => '../../Leanplum-iOS-SDK/'

  target 'Leanplum-iOS-Location_Tests' do
    pod 'OCMock', '~> 3.3.1'
  end
end

