inhibit_all_warnings!

target 'Leanplum-iOS-Location_Example' do
  platform :ios, '8.0'
  pod 'Leanplum-iOS-Location', :path => '../'
  pod 'Leanplum-iOS-SDK'
end

target 'Leanplum-iOS-LocationAndBeacons_Example' do
    platform :ios, '8.0'
    pod 'Leanplum-iOS-LocationAndBeacons', :path => '../'
    pod 'Leanplum-iOS-SDK'
    
    target 'Leanplum-iOS-Location_Tests' do
        pod 'OCMock', '~> 3.3.1'
    end
end

